### ISSUE TITLE
Subclass overriding methods that return/take `NSRange` not correctly generated

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/native#1180]
When generating code for `NSMutableIndexSet`, this code is produced:

```dart
final class _NSRange extends ffi.Struct {
  @NSUInteger()
  external int location;

  @NSUInteger()
  external int length;
}

typedef NSRange = _NSRange;

class NSMutableIndexSet extends objc.NSIndexSet {
  ...
  @override
  objc.NSIndexSet initWithIndexesInRange_(NSRange range) {
    final _ret =
        _objc_msgSend_16(this.pointer, _sel_initWithIndexesInRange_, range);
    return NSMutableIndexSet.castFromPointer(_ret, retain: true, release: true);
  }
  ...
}
```

But `package:objective_c defines `NSIndexSet` like:

```dart
class NSIndexSet extends NSObject {
   ...
  NSIndexSet initWithIndexesInRange_(_NSRange range) {
    final _ret =
        _objc_msgSend_118(this.pointer, _sel_initWithIndexesInRange_, range);
    return NSIndexSet.castFromPointer(_ret, retain: true, release: true);
  }
  ...
```

Since the `NSRange` used in the base and subclass don't match, the `@override` is not valid. Probably `NSRange` has to be part of `package:objective_c` and generated code must reference that.

**Comment by brianquinlan** [comment]
Maybe `NSMutableIndexSet` should be part of `package:objective_c`.

**Comment by brianquinlan** [comment]
Name issue for `NSSimpleCString` for these methods:
-  `initWithCharactersNoCopy_length_deallocator_` (because of `deallocator`)
- `initWithFormat_arguments_` (because of `va_list`)
- `initWithFormat_locale_arguments_` (because of `va_list`)
- `initWithValidatedFormat_validFormatSpecifiers_arguments_error_` (because of `va_list`)
- `initWithValidatedFormat_validFormatSpecifiers_locale_arguments_error_` (becase of `va_list`)
- `initWithBytesNoCopy_length_encoding_deallocator_` (because of `deallocator`)

**Comment by brianquinlan** [comment]
I think that you fixed this.

**Comment by liamappelbe** [comment]
Not sure if it's fixed, but package:objective_c should probably export the `NSRange` struct, and any other structs it defines.

**Comment by brianquinlan** [comment]
Doesn't `package:objective_c` have to export every type that appears anywhere in any API that it exports?

**Comment by liamappelbe** [comment]
Yep. I've exported all the interfaces, but not the structs.

**Comment by brianquinlan** [comment]
If you wanted to add a test that verifies that you have exported everything that you need to, you could use `dart:mirrors`.

**Comment by brianquinlan** [comment]
Ah, that would explain why the generated buildings are still incorrect:
```
  @override
  NSMutableIndexSet initWithIndexesInRange_(NSRange range) {
```

```
'NSMutableIndexSet.initWithIndexesInRange_' ('NSMutableIndexSet Function(_NSRange)') isn't a valid override of 'NSIndexSet.initWithIndexesInRange_' ('NSIndexSet Function(_NSRange)').
```

**Comment by liamappelbe** [comment]
Fixed this a while ago (https://github.com/dart-lang/native/pull/1175) but forgot to close it.

**Comment by BestOwl** [comment]
I can still reproduce this issue when generating code for `SFTranscriptionSegment` using the `ffigen` package version 14.0.1 and `objective_c` version 2.0.0.

**Comment by liamappelbe** [comment]
@BestOwl can you give me some more information? What buggy behavior are you seeing?

**Comment by BestOwl** [comment]
Use the following config to generate a bindings for `SFTranscriptionSegment`
``` yaml
ffigen:
  name: Speech
  description: Bindings for Apple Speech framework
  language: objc
  output: "lib/src/apple_speech_bindings_generated.dart"
  headers:
    entry-points:
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Speech.framework/Headers/Speech.h"
  exclude-all-by-default: true
  objc-interfaces:
    include:
      - SFTranscriptionSegment
  ```
  
ffigen produces the warning: 
```
[WARNING]: Generated declaration '_NSRange' starts with '_' and therefore will be private.
```
and the generated code: 
```
final class _NSRange extends ffi.Struct {
  @ffi.UnsignedLong()
  external int location;

  @ffi.UnsignedLong()
  external int length;
}

...

/// SFTranscriptionSegment
class SFTranscriptionSegment extends objc.NSObject {

...

  /// substringRange
  void getSubstringRange(ffi.Pointer<_NSRange> stret) {
    objc.useMsgSendVariants
        ? _objc_msgSend_437Stret(stret, this.ref.pointer, _sel_substringRange)
        : stret.ref = _objc_msgSend_437(this.ref.pointer, _sel_substringRange);
  }

...

}

```

The generated code should use `NSRange` from `package:objective_c` instead
